# python ./tools/extract_flow_feature.py /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/met  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/met_flow.h5
# python ./tools/extract_flow_feature.py /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/bbt  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/bbt_flow.h5
# python ./tools/extract_flow_feature.py /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/grey  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/grey_flow.h5
# python ./tools/extract_flow_feature.py /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/friends  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/friends_flow.h5
# python ./tools/extract_flow_feature.py /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/house  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/house_flow.h5
# python ./tools/extract_flow_feature.py /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/castle  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/castle_flow.h5

python ./tools/extract_flow_feature.py /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/met  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/met_flow_hmdb51_scores.h5
python ./tools/extract_flow_feature.py /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/bbt  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/bbt_flow_hmdb51_scores.h5
python ./tools/extract_flow_feature.py /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/grey  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/grey_flow_hmdb51_scores.h5
python ./tools/extract_flow_feature.py /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/friends  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/friends_flow_hmdb51_scores.h5
python ./tools/extract_flow_feature.py /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/house  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/house_flow_hmdb51_scores.h5
python ./tools/extract_flow_feature.py /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/castle  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/castle_flow_hmdb51_scores.h5