# python ./tools/extract_visual_feature.py places /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/bbt  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/bbt_places.h5
# python ./tools/extract_visual_feature.py places /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/met  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/met_places.h5
# python ./tools/extract_visual_feature.py places /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/grey  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/grey_places.h5
# python ./tools/extract_visual_feature.py places /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/friends  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/friends_places.h5
# python ./tools/extract_visual_feature.py places /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/house  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/house_places.h5
# python ./tools/extract_visual_feature.py places /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/castle  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/castle_places.h5

# python ./tools/extract_visual_feature.py places /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/bbt  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/bbt_places_score.h5
python ./tools/extract_visual_feature.py places /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/met  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/met_places_score.h5
python ./tools/extract_visual_feature.py places /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/grey  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/grey_places_score.h5
python ./tools/extract_visual_feature.py places /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/friends  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/friends_places_score.h5
python ./tools/extract_visual_feature.py places /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/house  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/house_places_score.h5
python ./tools/extract_visual_feature.py places /net/bvisionserver4/playpen1/jielei/data/preprocessed_video_data/dense_flow_frames/castle  /net/bvisionserver4/playpen10/jielei/data/dense_flow_features/castle_places_score.h5
